### ISSUE TITLE
About reproducing

### ISSUE THREAD

**Issue by hmep313** [Zhanxin-Gao/CPrompt#5]
Hi,thanks for your nice work! 
I tried to reproduce the results about StanfordCars but there is an error :

Traceback (most recent call last):
  File "main.py", line 27, in <module>
    main()
  File "main.py", line 10, in main
    train(args)
  File "/root/autodl-tmp/CPrompt-main/CPrompt-main/trainer.py", line 17, in train
    _train(args)
  File "/root/autodl-tmp/CPrompt-main/CPrompt-main/trainer.py", line 32, in _train
    model = factory.get_model(args['model_name'], args)
  File "/root/autodl-tmp/CPrompt-main/CPrompt-main/utils/factory.py", line 6, in get_model
    return CPrompt(args)
  File "/root/autodl-tmp/CPrompt-main/CPrompt-main/models/cprompt.py", line 36, in __init__
    self._network=CPrompt_Net(self.args)
  File "/root/autodl-tmp/CPrompt-main/CPrompt-main/network/cprompt_net.py", line 61, in __init__
    self.image_encoder =_create_vision_transformer('vit_base_patch16_224', pretrained=True, **model_kwargs)
  File "/root/autodl-tmp/CPrompt-main/CPrompt-main/network/cprompt_net.py", line 25, in _create_vision_transformer
    default_num_classes = pretrained_cfg['num_classes']
TypeError: 'PretrainedCfg' object is not subscriptable

what is the problem here?

**Comment by Zhanxin-Gao** [comment]
Hi,
You may need to check the network connection of your server host.

**Comment by Ethanhuhuhu** [comment]
Hi @hmep313 , I got the same traceback and I solved it by downgrading the timm. It should be downgraded to 0.6.11 and it works.

**Comment by hmep313** [comment]
@Ethanhuhuhu thank you so much!
